### ISSUE TITLE
Is there any way to define per project REPL?

### ISSUE THREAD

**Issue by rafaelleru** [pappasam/nvim-repl#12]
Hi, is there any possibility or workaround to define a specific repl in a project. My use case is that I have a project where I want to run code inside a docker container and not in my local python environment. Setting the REPL to docker exec -it <container> bpython works, so I only need a workaround to set that only for my project.

**Comment by pappasam** [comment]
If you're on the latest neovim (0.9+), I recommend looking into the new secure exrc functionality. Let me know if that ends up working for you!

**Comment by pappasam** [comment]
If on a previous version, here's a plug-in: https://github.com/MunifTanjim/exrc.nvim
