### ISSUE TITLE
tmux target

### ISSUE THREAD

**Issue by gauteh** [pappasam/nvim-repl#15]
Hi,

thank you for this great plugin! Is there any chance of using a tmux pane as target for e.g. the ipython repl?

Regards, Gaute

**Comment by gauteh** [comment]
Maybe this can be done with using `:Twrite` from vim-tbone as driver for repl#send_block

**Comment by pappasam** [comment]
After thinking about this for a while, I don't think this is something nvim-repl should support. It would add a lot of complexity to the codebase and it's a fundamentally different user experience than is intended (I like keeping my projects very limited in scope to reduce overall maintenance burden). Thanks for submitting this issue and I hope you're able to find support for this usecase (I also use Tmux!)
