### ISSUE TITLE
the same repl is used for all buffers / tabs etc

### ISSUE THREAD

**Issue by gauteh** [pappasam/nvim-repl#16]
opening a new tab with a different file I would expect it to keep it's independent 'kernel', now everything is run in the same terminal. maybe it should be on 'buf' or 'window' level.

**Comment by pappasam** [comment]
Yep, this is definitely a limitation. That said, this decision has dramatically reduced our bug exposure. In general, I'll just fire up another neovim instance if I really need two terminals running.
