### ISSUE TITLE
Use with an external terminal

### ISSUE THREAD

**Issue by avidseeker** [pappasam/nvim-repl#21]
Using external terminal, rather than nvim-emulated terminal, might be preferred.

E.g: qtconsole provides better graphics support for cell output.

**Comment by avidseeker** [comment]
I found this plugin to do exactly what I needed:

https://github.com/jupyter-vim/jupyter-vim

**Comment by pappasam** [comment]
External terminals are outside the scope of this project, but I'm glad you sound something that works!
