### ISSUE TITLE
Failed Cells Detection in Haskell

### ISSUE THREAD

**Issue by mostafatouny** [pappasam/nvim-repl#22]
Hello,

Thank you for the supremely beautiful. It perfectly worked with Julia programming language.

It worked with Haskell but detecting cells failed. When the cursor was on first cell, Running `<Plug>ReplSendCell` considered the whole file.

![Screenshot_2024-05-25_15-04-43](https://github.com/pappasam/nvim-repl/assets/56471405/1463ddb7-d829-47e0-9c9d-924c99299bdb)

The following produced the same output.
```
-- # %% first cell
head [1, 5, 7]

-- # %% second
head [5, 5]
```

The following correctly detected cells but running the whole file produces syntax error.
```
# %% first cell
head [1, 5, 7]

# %% second
head [5, 5]
```

**Comment by pappasam** [comment]
Sorry for taking so long to get to this, this should be resolved now
