### ISSUE TITLE
Feature Request: Command to send a command to the Repl

### ISSUE THREAD

**Issue by thays42** [pappasam/nvim-repl#24]
This is a request for a command, e.g., `:ReplSend`, that takes code that would be immediately run. When working in R, it can be handy to bind a key to sending a specific command to the terminal, e.g., `:ReplSend devtools::load_all()`.

Thanks for your work on this!

**Comment by pappasam** [comment]
Resolved by adding `ReplSendArgs` in e8f9d5019b99c93cb7a288382338aff3c2bc9d19
