### ISSUE TITLE
lazy nvim package manager and nvim-repl

### ISSUE THREAD

**Issue by leet0rz** [pappasam/nvim-repl#25]
I can't seem to figure out how to use lazy nvim plugin manager on this one, do you have some template code on how to install this via lazy nvim? The following does not seem to work which work with most other plugins:
```lua
    {
        "pappasam/nvim-repl",
        config = function()
            require("nvim-repl").setup()
        end
    },
```

**Comment by pappasam** [comment]
@leet0rz Based on lazy's documentation, I've added instructions in the readme as of 57536eedae7e2cc40ff27091402c9cdb7cb7a0d6. Please let me know if they work for you.
