### ISSUE TITLE
[feature-request] Plot Images within IPython REPL

### ISSUE THREAD

**Issue by shoaibkhanz** [pappasam/nvim-repl#26]
It would be highly beneficial to have support for inline plotting within IPyKernel in Neovim, similar to the capability discussed in [Vigemus/iron.nvim#381](https://github.com/Vigemus/iron.nvim/issues/381). This feature would enable users to view plots directly within Neovim when running a Jupyter or IPython kernel, providing a more seamless experience for data analysis and visualization.

**Expected Behavior**

1. **Inline Plotting Support:** Enable inline plotting within Neovim when connected to an IPyKernel. Users should see visual outputs (e.g., matplotlib plots) directly within the Neovim buffer.
2. **TMUX Compatibility:** Ensure that the inline plotting feature works seamlessly within TMUX sessions. This would enable a smooth workflow across terminal-based environments.

**Comment by pappasam** [comment]
While I fully support this feature being available to all users, its implementation is out of scope for this project. `nvim-repl` sends text to, and executes that text in, Neovim's built-in terminal in an ergonomic way. It is the responsibility of the built-in terminal itself (and also the user's terminal emulator) to render images.

**Comment by pappasam** [comment]
Many popular terminal emulators do not support Sixel, including the one I use (Alacritty). Hopefully that changes someday: https://www.arewesixelyet.com/

**Comment by pappasam** [comment]
Also see: https://github.com/neovim/neovim/issues/30889
