### ISSUE TITLE
sending a cell does not work in ocaml

### ISSUE THREAD

**Issue by mostafatouny** [pappasam/nvim-repl#27]
Hello,
sending a line worked with [ocaml](https://ocaml.org/docs/toplevel-introduction) but sending a cell did not. See ocaml's comments syntax [here](https://www.w3schools.io/languages/ocaml-comments/).

![Screenshot_2024-12-12_11-09-11](https://github.com/user-attachments/assets/588733ad-c691-4525-9fd8-ba0fc6678366)

**Comment by pappasam** [comment]
Fixed in https://github.com/pappasam/nvim-repl/commit/4a365674dd3b2dea173b32558316e8ef4f82ed0a , thanks for opening this clear issue!
