### ISSUE TITLE
Python Virtual Environments and Navigating windows

### ISSUE THREAD

**Issue by ECon87** [pappasam/nvim-repl#3]
Hi,

Great plugin. Two questions:

1. How can I work within a python virtual environment?

2. Once in the repl window, I cannot move back to the editor using the keyboard. How can I fix this?

Cheers.

**Comment by pappasam** [comment]
1. You need to do 2 things. First, make sure that your virtualenv is activated when you open Vim. Second, make sure you've installed the executable you're running (bpython, etc) in your virtualenv
2. As long as you're only in the repo window, your regular navigation keys should work (`<C-w>j`, `<C-w>h`, etc). If you've entered INSERT mode within the repl, you'll need to escape using the weird Neovim-specific keybinding `<C-\><C-n>.` Don't blame me, I didn't choose that :p 

Hope everything works out for you!

**Comment by ECon87** [comment]
Thank you that worked like a charm. And thanks again for the great plugin. I was looking for a minimal repl plugin for neovim for a while.
